FeedbackBundle\Entity\Goal:
    type: entity
    table: goals
    repositoryClass: FeedbackBundle\Repository\GoalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:
            type: text
            nullable: false

        description:
            type: text
            nullable: false

        progress:
            type: float
            nullable: false

        startDate:
            type: date
            nullable: false

        endDate:
            type: date
            nullable: false
    manyToOne:
        user:
          targetEntity: UserBundle\Entity\User
          inversedBy: goals
          joinColumn:
            name: user_id
            referencedColumnName: id