FOS\UserBundle\Form\Model\ChangePassword:
    properties:
        new:
            - NotBlank: ~
            - Regex: 
                pattern: '/(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}/'
                message: Password does not meet the requirements.
                groups: [Registration, ResetPassword, ChangePassword]
                