# Sonata Core Bundle Configuration
sonata_core: ~

# Sonata Cache Bundle Configuration
sonata_cache:
    caches:
        predis:
            servers:
                - { host: 127.0.0.1, port: 6379, database: 42 }

# Sonata Block Bundle Configuration
sonata_block:
    default_contexts: [symfony-demo]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:
        sonata.block.service.template:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        # sonata.block.advance_requests: ~
        zitec.admin.block.tile:

# Sonata Admin Configuration
sonata_admin:
    title:      'Symfony 2.8 Demo'
    title_logo: image/logo-small.png
    options:
        pager_links: 10
        html5_validate: false
    persist_filters: true
    templates:
        add_block:  AdminIntegrationBundle:Core:add_block.html.twig
        list_block: AdminIntegrationBundle:Block:block_admin_list.html.twig
        ajax:       AdminIntegrationBundle::ajax_layout.html.twig
        dashboard:  AdminIntegrationBundle:Core:dashboard.html.twig
        layout:     AdminIntegrationBundle::standard_layout.html.twig
        user_block: AdminIntegrationBundle:Block:block_user.html.twig
        batch:      AdminIntegrationBundle:CRUD:list__batch.html.twig
        list:       AdminIntegrationBundle:CRUD:list.html.twig
        edit:       AdminIntegrationBundle:CRUD:edit.html.twig
        history:    AdminIntegrationBundle:CRUD:base_history.html.twig
    security:
        handler: sonata.admin.security.handler.noop
