imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: users.yml }
    - { resource: admin.yml }
    - { resource: "@TestBundle/Resources/config/services.yml" }
    - { resource: "@FeedbackBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed (different enviroment) 
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AdminIntegrationBundle, UserBundle, FOSUserBundle, TestBundle ]

    filters:
        cssrewrite: ~
        jsqueeze: ~

    assets:
        bootstrap:
            inputs:
                - libs/css/bootstrap.css
        jquery:
            inputs:
                - libs/js/jquery-1.11.0.min.js
        bootstrap_js:
            inputs:
                - libs/js/bootstrap.js
        jquery_validate:
            inputs:
                - libs/js/jquery.validate.js
        boekkooi_jquery_validation_bundle:
            inputs:
                - @BoekkooiJqueryValidationBundle/Resources/public/additional-methods.min.js

        select2_css:
            inputs:
                - libs/css/select2.min.css

        select2_js:
            inputs:
                - libs/js/select2/select2.full.min.js
                - libs/js/select2/translation-ro.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
