# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN #just to be able to see the left side menu
        ROLE_HYPER_ADMIN:
            - ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                default_target_path: sonata_admin_redirect

            remember_me:
                key:      '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

            logout:       true
            anonymous:    true

            # SonataUserBundle impersonating feature
            switch_user: { role: ROLE_ADMIN }

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
