# ORM definition of the User model.
UserBundle\Entity\Group:
    type: entity
    table: users_groups
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        baseQuestions:
            targetEntity: FeedbackBundle\Entity\BaseQuestion
            mappedBy: group

    manyToMany:
      users:
        targetEntity: User
        mappedBy: groups
