# The bundle's custom blocks.
services:
    adminintegrationbundle.block.toolbar:
        class: AdminIntegrationBundle\Block\Toolbar
        arguments:
            - adminintegrationbundle.block.toolbar
            - @templating
        tags:
            - { name: sonata.block }
