homepage:
    path:     /
    defaults: { _controller: FeedbackBundle:Default:index }

show_my_goals_section:
    path:     /goals/show_my_goals
    defaults: { _controller: FeedbackBundle:Goal:showMyGoals }

show_goals_page:
    path:   /goals
    defaults: { _controller: FeedbackBundle:Goal:myGoalsPage }

remove_goal_action:
    path:   /goals/remove
    defaults: { _controller: FeedbackBundle:Goal:removeGoal }

edit_goal_action:
    path:   /goals/edit/{id}
    defaults: { _controller: FeedbackBundle:Goal:editGoal }

add_goal_action:
    path:   /goals/add
    defaults: { _controller: FeedbackBundle:Goal:addGoal }