homepage:
    path:     /
    defaults: { _controller: FeedbackBundle:Default:index }

about_page:
    path:   /about
    defaults: { _controller: FeedbackBundle:Default:aboutPage }

show_my_goals_section:
    path:     /goals/show_my_goals
    defaults: { _controller: FeedbackBundle:Goal:showMyGoals }

show_goals_page:
    path:   /goals
    defaults: { _controller: FeedbackBundle:Goal:myGoalsPage }

remove_goal_action:
    path:   /goals/remove
    defaults: { _controller: FeedbackBundle:Goal:removeGoal }

edit_goal_action:
    path:   /goals/edit/{id}
    defaults: { _controller: FeedbackBundle:Goal:editGoal }

add_goal_action:
    path:   /goals/add
    defaults: { _controller: FeedbackBundle:Goal:addGoal }

add_recognition_action:
    path:   /recognition/add
    defaults: { _controller: FeedbackBundle:Recognition:add }

edit_recognition_action:
    path:   /recognition/edit/{id}
    defaults: { _controller: FeedbackBundle:Recognition:edit }

remove_recognition_action:
    path:   /recognition/remove
    defaults: { _controller: FeedbackBundle:Recognition:remove }

list_recognition_action:
    path:   /recognition/list
    defaults: { _controller: FeedbackBundle:Recognition:list }

show_my_recognition_action:
    path:   /recognition/my-recognitions
    defaults: { _controller: FeedbackBundle:Recognition:myRecognition }

show_company_recognition_action:
    path:  /recognition/company-recognitions/{page}
    defaults: { _controller: FeedbackBundle:Recognition:companyRecognitions, page: 1}

show_my_feedback_session_action:
    path:  /session/show_my_session_section
    defaults: { _controller: FeedbackBundle:Feedback:getActiveFeedbackSection }

feedback_session_handler_action:
    path:   /session/feedback/{id}
    defaults: { _controller: FeedbackBundle:Feedback:sessionHandler }

show_my_feedback:
    path:   /session/my-feedback
    defaults: { _controller: FeedbackBundle:Feedback:showSessions }
show_my_score:
    path:  /session/current-user-score
    defaults: { _controller: FeedbackBundle:Feedback:currentUserScore }