services:
    feedback_bundle.admin.goal_admin:
        class: FeedbackBundle\Admin\GoalAdmin
        arguments:
            - ~
            - FeedbackBundle\Entity\Goal
            - ~
        tags:
          - { name: sonata.admin, manager_type: orm, label: "Goal", group: "Activities" }
        calls:
          - [setTranslationDomain, [admin]]